services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=famstar
      - POSTGRES_USER=famstar
      - POSTGRES_PASSWORD=helloworld
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./docker-db-init:/docker-entrypoint-initdb.d"
    networks:
      - db

  server:
    build: .
    env_file: .env
    depends_on:
      - postgres
    ports: 
      - "8800:8800"
    volumes:
      - type: bind
        source: ./data-test
        target: /data
    networks:
      - db

volumes:
  pgdata:
    external: true

networks:
  db: